name: Static Analysis (Linting, License, Type checks...)

on:
    pull_request:
    push:
        branches:
            - trunk
            - 'release/**'
            - 'wp/**'

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
    # The concurrency group contains the workflow name and the branch name for pull requests
    # or the commit hash for any other events.
    group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
    cancel-in-progress: true

jobs:
    check:
        name: All
        runs-on: ubuntu-latest
        if: ${{ github.repository == 'WordPress/gutenberg' || github.event_name == 'pull_request' }}

        steps:
            - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # v2.3.4
            - uses: pnpm/action-setup@v2.0.1
              with:
                  version: 6.23.6
            - name: Use desired version of NodeJS
              uses: actions/setup-node@v2
              with:
                  node-version: 14
                  cache: pnpm

            - name: Npm install
              run: pnpm install

            - name: Lint JavaScript and Styles
              run: npm run lint

            - name: Type checking
              run: npm run build:package-types

            - name: Check local changes
              run: npm run check-local-changes

            - name: License compatibility
              run: npm run check-licenses
